// Theme Configuration
// Centralized theme definitions for the application

export const THEMES = {
    dark: {
        id: 'dark',
        name: 'Dark (Default)',
        bg: 'bg-black',
        nav: 'bg-[#0f1115]',
        card: 'bg-gray-900 border-gray-800',
        cardHeader: 'bg-gray-900/50 border-gray-800',
        text: 'text-white',
        subText: 'text-gray-400',
        accent: 'text-orange-500',
        button: 'bg-gray-800 hover:bg-gray-700 text-gray-300',
        buttonPrimary: 'bg-blue-600 hover:bg-blue-700 text-white',
        buttonSecondary: 'bg-purple-600 hover:bg-purple-700 text-white',
        buttonSuccess: 'bg-green-600 hover:bg-green-700 text-white',
        buttonDisabled: 'bg-gray-700 text-gray-500',
        icon: 'text-gray-500 hover:text-white',
        iconAccent: 'text-blue-500',
        selectorContainer: 'bg-gray-900/40 border-gray-800',
        rawData: 'bg-gray-950 border-gray-800 text-gray-400',
        tableRowHover: 'hover:bg-gray-900',
        modalOverlay: 'bg-black/80 backdrop-blur-sm',
        modalBg: 'bg-gray-900',
        modalBorder: 'border-gray-700',
        modalHeaderBg: 'bg-gray-950/50',
        modalText: 'text-gray-100',
        modalTitle: 'text-white',
        modalCloseIcon: 'text-gray-400 hover:text-white',
        sectionHeader: 'bg-gray-900 border-gray-700',
        dropdown: {
            bg: 'bg-gray-900',
            border: 'border-gray-700',
            menuBg: 'bg-gray-800',
            menuBorder: 'border-gray-700',
            hover: 'hover:bg-gray-700',
            text: 'text-gray-300',
            active: 'bg-blue-600 text-white',
            label: 'text-gray-400',
            placeholder: 'text-gray-500',
            inputText: 'text-white',
            focused: 'bg-gray-700 text-white'
        },
        sidebar: {
            container: 'bg-gray-900 border-gray-800',
            header: 'border-gray-800',
            headerText: 'text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-amber-200',
            headerSubText: 'text-gray-500',
            menuLabel: 'text-gray-600',
            itemInactive: 'text-gray-400 hover:bg-gray-800/50 hover:text-white',
            itemActive: 'bg-gray-800 text-white shadow-lg border border-gray-700/50',
            itemIconActive: 'text-white', // Use specific color in active state?
            footer: 'border-gray-800 bg-gray-900/50',
            collapseButton: 'text-gray-400 hover:bg-gray-800 hover:text-white border-transparent hover:border-gray-700',
            logoutButton: 'text-red-400 hover:bg-red-900/20 hover:text-red-300 border-transparent hover:border-red-900/30'
        }
    },
    pastel: {
        id: 'pastel',
        name: 'Pink Pastel',
        bg: 'bg-pink-50',
        nav: 'bg-pink-100 border-b border-pink-200',
        card: 'bg-white border-pink-200 shadow-md ring-1 ring-pink-100',
        cardHeader: 'bg-pink-50 border-pink-100',
        text: 'text-pink-900',
        subText: 'text-pink-500',
        accent: 'text-pink-600',
        button: 'bg-white hover:bg-pink-50 text-pink-600 border border-pink-200 shadow-sm',
        buttonPrimary: 'bg-pink-400 hover:bg-pink-500 text-white shadow-sm border border-pink-400',
        buttonSecondary: 'bg-purple-400 hover:bg-purple-500 text-white shadow-sm border border-purple-400',
        buttonSuccess: 'bg-green-400 hover:bg-green-500 text-white shadow-sm border border-green-400',
        buttonDisabled: 'bg-pink-100 text-pink-300 border border-pink-100',
        icon: 'text-pink-400 hover:text-pink-600',
        iconAccent: 'text-pink-500',
        selectorContainer: 'bg-white border-pink-200 shadow-sm',
        rawData: 'bg-pink-50/50 border-pink-200 text-pink-800',
        tableRowHover: 'hover:bg-pink-50',
        modalOverlay: 'bg-pink-900/40 backdrop-blur-md',
        modalBg: 'bg-white',
        modalBorder: 'border-pink-200',
        modalHeaderBg: 'bg-pink-50',
        modalText: 'text-pink-900',
        modalTitle: 'text-pink-800',
        modalCloseIcon: 'text-pink-400 hover:text-pink-600',
        sectionHeader: 'bg-white border-pink-200',
        dropdown: {
            bg: 'bg-white',
            border: 'border-pink-300',
            menuBg: 'bg-white',
            menuBorder: 'border-pink-200',
            hover: 'hover:bg-pink-50',
            text: 'text-pink-800',
            active: 'bg-pink-400 text-white',
            label: 'text-pink-500 font-semibold',
            placeholder: 'text-pink-300',
            inputText: 'text-pink-900',
            focused: 'bg-pink-100 text-pink-900'
        },
        sidebar: {
            container: 'bg-pink-100 border-pink-200', // SDB theme: bg-pink-50
            header: 'border-pink-200 bg-pink-50/50',
            headerText: 'text-pink-600',
            headerSubText: 'text-pink-400',
            menuLabel: 'text-pink-400',
            itemInactive: 'text-pink-500 hover:bg-white/60 hover:text-pink-700',
            itemActive: 'bg-white text-pink-600 shadow-sm border border-pink-200 font-bold',
            itemIconActive: 'text-pink-500',
            footer: 'border-pink-200 bg-pink-50/50',
            collapseButton: 'text-pink-400 hover:bg-white hover:text-pink-600 border-transparent hover:border-pink-200',
            logoutButton: 'text-red-400 hover:bg-red-50 hover:text-red-500 border-transparent hover:border-red-100'
        }
    },
    corporate: {
        id: 'corporate',
        name: 'Corporate Blue',
        bg: 'bg-slate-50',
        nav: 'bg-slate-900 border-b border-slate-800 shadow-md', // Dark nav for contrast
        text: 'text-slate-800', // Default text color
        navText: 'text-white', // Specific text color for nav elements if needed (custom property)
        card: 'bg-white border-slate-200 shadow-sm',
        cardHeader: 'bg-slate-50 border-slate-200',
        text: 'text-slate-800',
        subText: 'text-slate-500',
        accent: 'text-blue-600',
        button: 'bg-white hover:bg-slate-50 text-slate-700 border border-slate-300 shadow-sm',
        buttonPrimary: 'bg-blue-600 hover:bg-blue-700 text-white shadow-sm',
        buttonSecondary: 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm',
        buttonSuccess: 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-sm',
        buttonDisabled: 'bg-slate-100 text-slate-400 border border-slate-200',
        icon: 'text-slate-400 hover:text-blue-600',
        iconAccent: 'text-blue-500',
        selectorContainer: 'bg-white border-slate-200 shadow-sm',
        rawData: 'bg-slate-100 border-slate-200 text-slate-600',
        tableRowHover: 'hover:bg-slate-50',
        modalOverlay: 'bg-slate-900/40 backdrop-blur-sm',
        modalBg: 'bg-white',
        modalBorder: 'border-slate-200',
        modalHeaderBg: 'bg-slate-50',
        modalText: 'text-slate-800',
        modalTitle: 'text-slate-900',
        modalCloseIcon: 'text-slate-400 hover:text-slate-600',
        sectionHeader: 'bg-slate-50 border-slate-200',
        dropdown: {
            bg: 'bg-white',
            border: 'border-slate-300',
            menuBg: 'bg-white',
            menuBorder: 'border-slate-200',
            hover: 'hover:bg-slate-50',
            text: 'text-slate-700',
            active: 'bg-blue-600 text-white',
            label: 'text-slate-500 font-semibold',
            placeholder: 'text-slate-400',
            inputText: 'text-slate-900',
            focused: 'bg-blue-50 text-blue-900'
        },
        sidebar: {
            container: 'bg-slate-900 border-r border-slate-800',
            header: 'border-slate-800 bg-slate-950/30',
            headerText: 'text-white font-bold',
            headerSubText: 'text-slate-400',
            menuLabel: 'text-slate-500 uppercase tracking-wider font-semibold text-[10px]',
            itemInactive: 'text-slate-400 hover:bg-slate-800 hover:text-white',
            itemActive: 'bg-blue-600 text-white shadow-md border-r-4 border-blue-400 font-medium',
            itemIconActive: 'text-white',
            footer: 'border-slate-800 bg-slate-950/50',
            collapseButton: 'text-slate-500 hover:bg-slate-800 hover:text-white border-transparent hover:border-slate-700',
            logoutButton: 'text-red-400 hover:bg-red-900/20 hover:text-red-300 border-transparent hover:border-red-900/30'
        }
    }
};
