export const REPORT_VARIABLES = [
    { name: '@DAY', desc: 'วันที่ปัจจุบัน (1-31)', example: '17', category: 'Time' },
    { name: '@MONTH', desc: 'เดือนปัจจุบัน (ภาษาไทย)', example: 'กุมภาพันธ์', category: 'Time' },
    { name: '@YEAR', desc: 'ปี พ.ศ. ปัจจุบัน', example: '2569', category: 'Time' },
    { name: '@FULL_DATE', desc: 'วันที่แบบเต็ม (ไทย)', example: '17 กุมภาพันธ์ 2569', category: 'Time' },
    { name: '@TIME_RANGE', desc: 'ช่วงเวลาของข้อมูลในรายงาน', example: '16/02/69 - 17/02/69', category: 'Time' },
    { name: '@DOMAIN', desc: 'ชื่อโดเมน (หรือ "ทุก Subdomain")', example: 'example.com', category: 'Info' },
    { name: '@ACCOUNT_NAME', desc: 'ชื่อ Account Cloudflare', example: 'My Company', category: 'Info' },
    { name: '@ZONE_NAME', desc: 'ชื่อ Zone', example: 'example.com', category: 'Info' },
    { name: '@TOTAL_REQ', desc: 'จำนวน Request ทั้งหมด', example: '1,234,567', category: 'Stats' },
    { name: '@SUBDOMAIN_TOTAL_REQ_M', desc: 'จำนวน Request ทั้งหมดในหน่วยล้าน (เช่น 39.06M)', example: '39.06M', category: 'Stats' },
    { name: '@ZONE_TOTAL_REQ_M', desc: 'Total Request ของ Zone ในหน่วยล้าน (เช่น 39.06M)', example: '39.06M', category: 'Stats' },
    { name: '@PAGE_VIEWS_M', desc: 'จำนวน Page Views ทั้งหมดในหน่วยล้าน (เช่น 7.98M)', example: '7.98M', category: 'Stats' },
    { name: '@TRAFFIC_CHANGE_TEXT', desc: 'แนวโน้มการเปลี่ยนแปลง Traffic (เช่น เพิ่มขึ้น / ลดลง)', example: 'เพิ่มขึ้น', category: 'Stats' },
    { name: '@TRAFFIC_CHANGE_PCT', desc: 'เปอร์เซ็นต์การเปลี่ยนแปลงของ Traffic (เทียบกับรอบก่อนหน้า)', example: '1.79%', category: 'Stats' },
    { name: '@AVG_TIME', desc: 'เวลาตอบสนองเฉลี่ย (วินาที)', example: '0.450', category: 'Stats' },
    { name: '@BLOCK_PCT', desc: 'เปอร์เซ็นต์การ Block', example: '12.50', category: 'Stats' },
    { name: '@LOG_PCT', desc: 'เปอร์เซ็นต์การ Log', example: '5.00', category: 'Stats' },
    { name: '@PEAK_TIME', desc: 'เวลาที่มีการใช้งานสูงสุด', example: '14:30', category: 'Peak' },
    { name: '@PEAK_COUNT', desc: 'จำนวน Request สูงสุด ณ เวลา Peak', example: '5,000', category: 'Peak' },
    { name: '@PEAK_ATTACK_TIME', desc: 'เวลาที่มีการโจมตีสูงสุด', example: '02:15', category: 'Peak' },
    { name: '@PEAK_ATTACK_COUNT', desc: 'จำนวนการโจมตีสูงสุด', example: '800', category: 'Peak' },
    { name: '@PEAK_HTTP_TIME', desc: 'เวลาที่มี HTTP Status (Error) สูงสุด', example: '10:00', category: 'Peak' },
    { name: '@PEAK_HTTP_COUNT', desc: 'จำนวน HTTP Status สูงสุด', example: '200', category: 'Peak' },
    { name: '@TOP_UA_AGENT', desc: 'User Agent ที่พบบ่อยที่สุด', example: 'Mozilla/5.0...', category: 'Top' },
    { name: '@TOP_UA_COUNT', desc: 'จำนวนครั้งของ User Agent นั้น', example: '15,000', category: 'Top' },
    { name: '@TOP_IP_VAL', desc: 'IP ที่ใช้งานมากที่สุด (อันดับ 1)', example: '192.168.1.1', category: 'Top' },
    { name: '@TOP_UA_VAL', desc: 'User Agent อันดับ 1', example: 'Chrome...', category: 'Top' },
    { name: '@TOP_COUNTRY_VAL', desc: 'ประเทศที่ใช้งานมากที่สุด (อันดับ 1)', example: 'Thailand', category: 'Top' },
    { name: '@TOP_HOST_VAL', desc: 'Host ที่ถูกเรียกมากที่สุด (อันดับ 1)', example: 'api.example.com', category: 'Top' },
    { name: '@TOP_URLS_LIST', desc: 'ตาราง 3 อันดับ URL ยอดนิยม', example: '<table>...</table>', category: 'Table' },
    { name: '@TOP_IPS_LIST', desc: 'ตาราง 3 อันดับ Client IP', example: '<table>...</table>', category: 'Table' },
    { name: '@TOP_RULES_LIST', desc: 'ตาราง 3 อันดับ WAF Rule ที่ทำงาน', example: '<table>...</table>', category: 'Table' },
    { name: '@TOP_ATTACKERS_LIST', desc: 'ตาราง 5 อันดับผู้โจมตี', example: '<table>...</table>', category: 'Table' },
    { name: '@TOP_SOURCES_LIST', desc: 'ตาราง 5 อันดับ Security Source', example: '<table>...</table>', category: 'Table' },
    { name: '@TOP_PATHS_LIST', desc: 'รายการ Top 5 Paths (List)', example: '<ol>...</ol>', category: 'List' },
    { name: '@TOP_CUSTOM_RULES_LIST', desc: 'รายการ Top Custom Rules (List)', example: '<ol>...</ol>', category: 'List' },
    { name: '@TOP_MANAGED_RULES_LIST', desc: 'รายการ Top Managed Rules (List)', example: '<ol>...</ol>', category: 'List' },
    { name: '@ZONE_TOTAL_REQ', desc: 'Total Request ของ Zone (Caching)', example: '10M', category: 'Zone Cache' },
    { name: '@ZONE_CACHE_HIT_REQ', desc: 'Cache Hit Requests', example: '8M', category: 'Zone Cache' },
    { name: '@ZONE_CACHE_HIT_REQ_RATIO', desc: 'Ratio Cache Hit Requests', example: '80%', category: 'Zone Cache' },
    { name: '@ZONE_TOTAL_BANDWIDTH', desc: 'Total Bandwidth', example: '50 GB', category: 'Zone Cache' },
    { name: '@ZONE_CACHE_HIT_BANDWIDTH', desc: 'Cache Hit Bandwidth', example: '20 GB', category: 'Zone Cache' },
    { name: '@ZONE_CACHE_HIT_BANDWIDTH_RATIO', desc: 'Ratio Cache Hit Bandwidth', example: '40%', category: 'Zone Cache' },
    { name: '@ZONE_TOP_COUNTRIES_REQ', desc: 'Top Countries by Request (List)', example: '<ol>...</ol>', category: 'Zone Cache' },
    { name: '@ZONE_TOP_COUNTRIES_BYTES', desc: 'Top Countries by Bytes (List)', example: '<ol>...</ol>', category: 'Zone Cache' },
    { name: '@FW_TOTAL_EVENTS', desc: 'รวมเหตุการณ์ Firewall ทั้งหมด', example: '150k', category: 'Firewall' },
    { name: '@FW_MANAGED_EVENTS', desc: 'Managed Rules Events', example: '10k', category: 'Firewall' },
    { name: '@FW_CUSTOM_EVENTS', desc: 'Custom Rules Events', example: '5k', category: 'Firewall' },
    { name: '@FW_BIC_EVENTS', desc: 'Browser Integrity Check Events', example: '1k', category: 'Firewall' },
    { name: '@FW_ACCESS_EVENTS', desc: 'Access Rules Events', example: '500', category: 'Firewall' },
    { name: '@FW_LOG_COUNT', desc: 'จำนวนการจัดการ Traffic แบบ Log (การบันทึก)', example: '1.43M', category: 'Firewall' },
    { name: '@FW_SKIP_COUNT', desc: 'จำนวนการจัดการ Traffic แบบ Skip (การข้ามตรวจสอบ)', example: '3.76k', category: 'Firewall' },
    { name: '@FW_CHALLENGE_COUNT', desc: 'จำนวนการจัดการ Traffic แบบ Managed Challenge (การท้าทายตรวจสอบ)', example: '6.1k', category: 'Firewall' },
    { name: '@FW_BLOCK_COUNT', desc: 'จำนวนการจัดการ Traffic แบบ Block (การปิดกั้น)', example: '0', category: 'Firewall' },
    { name: '@SUBDOMAIN_COUNT', desc: 'จำนวน Subdomain ทั้งหมดใน Zone', example: '15', category: 'Info' },
    { name: '@PROXIED_COUNT', desc: 'จำนวน Subdomain ที่เปิดใช้งาน Proxy', example: '8', category: 'Info' },
    { name: '@TOP_COUNTRY_REQ', desc: 'จำนวน Request จากประเทศที่ใช้งานมากที่สุด', example: '21,970,000', category: 'Top' },
    { name: '@VISITS', desc: 'จำนวนผู้เข้าชมทั้งหมด (Visits/Uniques)', example: '3,670,000', category: 'Stats' },
    { name: '@PAGE_VIEWS', desc: 'จำนวน Page Views ทั้งหมด', example: '7,980,000', category: 'Stats' },
    { name: '@REQ_PER_PAGEVIEW_PCT', desc: 'อัตราส่วน Request ต่อ Page View (%)', example: '489.47%', category: 'Stats' },
    { name: '@TOTAL_DATA_TRANSFER', desc: 'ปริมาณการโอนย้ายข้อมูลทั้งหมด (Data Transfer)', example: '2.46 TB', category: 'Stats' },
    { name: '@DATA_TRANSFER_CHANGE_TEXT', desc: 'แนวโน้มการเปลี่ยนแปลง Data Transfer (เช่น เพิ่มขึ้น / ลดลง)', example: 'ลดลง', category: 'Stats' },
    { name: '@DATA_TRANSFER_CHANGE_PCT', desc: 'เปอร์เซ็นต์การเปลี่ยนแปลงของ Data Transfer (เทียบกับรอบก่อนหน้า)', example: '17.43%', category: 'Stats' },
    { name: '@ARGO_IMPROVEMENT_PCT', desc: 'เปอร์เซ็นต์ประสิทธิภาพที่เพิ่มขึ้นโดยเฉลี่ยของ Argo', example: '29.84%', category: 'Argo' },
    { name: '@ARGO_RT_BEFORE', desc: 'Response Time จากทางฝั่ง Server ก่อนเปิดใช้ Argo', example: '1.15 s', category: 'Argo' },
    { name: '@ARGO_RT_AFTER', desc: 'Response Time จากทางฝั่ง Server หลังเปิดใช้ Argo', example: '804 ms', category: 'Argo' },
    { name: '@SPEED_TTI', desc: 'เวลาในการโต้ตอบหลัก (Time to Interactive) จากการทดสอบความเร็ว', example: '1,221 ms', category: 'Speed' },
    { name: '@SPEED_INDEX', desc: 'ความเร็วเฉลี่ยในการแสดงผลหน้าเว็บ (Speed Index)', example: '1,165 ms', category: 'Speed' },
    { name: '@SPEED_SCORE', desc: 'คะแนนประสิทธิภาพรวมในการทดสอบความเร็ว (%)', example: '97%', category: 'Speed' },
    { name: '@SPEED_LEVEL', desc: 'ระดับคะแนนประสิทธิภาพความเร็ว (เช่น ดีเยี่ยม / ดี / ปานกลาง)', example: 'ดีเยี่ยม', category: 'Speed' },
    { name: '@SPEED_MOBILE_TTI', desc: 'เวลาในการโต้ตอบหลักสำหรับมือถือ (Mobile Time to Interactive) จากการทดสอบความเร็ว', example: '5,924 ms', category: 'Speed' },
    { name: '@SPEED_MOBILE_INDEX', desc: 'ความเร็วเฉลี่ยในการแสดงผลหน้าเว็บสำหรับมือถือ (Mobile Speed Index)', example: '3,259 ms', category: 'Speed' },
    { name: '@SPEED_MOBILE_SCORE', desc: 'คะแนนประสิทธิภาพรวมสำหรับมือถือในการทดสอบความเร็ว (%)', example: '67%', category: 'Speed' },
    { name: '@SPEED_MOBILE_LEVEL', desc: 'ระดับคะแนนประสิทธิภาพความเร็วสำหรับมือถือ (เช่น ดีเยี่ยม / ดี / ปานกลาง / กลาง)', example: 'กลาง', category: 'Speed' },
    { name: '@PAGE_BREAK@', desc: 'ตัวคั่นหน้ากระดาษ (Word)', example: '<br page-break.../>', category: 'Format' },
    { name: '@DASHBOARD_IMAGE@', desc: 'รูปภาพ Dashboard Snapshot', example: '<img>', category: 'Format' },
    { name: '@TOC@', desc: 'สารบัญอัตโนมัติ (เลือกวางจุดใดก็ได้ในเทมเพลต)', example: '<div>...</div>', category: 'Format' },
    { name: '@captured_domain_page', desc: 'รูปภาพหน้าจอหน้ารวมโดเมน (Sites overview)', example: '<img>', category: 'Screenshots' },
    { name: '@captured_dns_page', desc: 'รูปภาพหน้าจอรายการ DNS Records', example: '<img>', category: 'Screenshots' },
    { name: '@captured_firewall_page', desc: 'รูปภาพหน้าจอความปลอดภัยและเหตุการณ์ WAF (Firewall Overview)', example: '<img>', category: 'Screenshots' },
    { name: '@captured_security_rules_page', desc: 'รูปภาพหน้าจอรายการกฎความปลอดภัย (Security Custom Rules)', example: '<img>', category: 'Screenshots' },
    { name: '@captured_argo_page', desc: 'รูปภาพหน้าจอการตั้งค่า Argo Smart Routing', example: '<img>', category: 'Screenshots' },
    { name: '@captured_speed_page', desc: 'รูปภาพหน้าจอผลการทดสอบความเร็วเว็บไซต์ (Speed Test)', example: '<img>', category: 'Screenshots' },
    { name: '@captured_speed_mobile_page', desc: 'รูปภาพหน้าจอผลการทดสอบความเร็วบนมือถือ (Speed Test Mobile)', example: '<img>', category: 'Screenshots' },
    { name: '@captured_request_traffic_page', desc: 'รูปภาพกราฟสถิติ HTTP Traffic เฉพาะ Requests', example: '<img>', category: 'Traffic Screenshots' },
    { name: '@captured_data_transfer_traffic_page', desc: 'รูปภาพกราฟสถิติ HTTP Traffic เฉพาะ Data Transfer', example: '<img>', category: 'Traffic Screenshots' },
    { name: '@captured_page_views_traffic_page', desc: 'รูปภาพกราฟสถิติ HTTP Traffic เฉพาะ Page Views', example: '<img>', category: 'Traffic Screenshots' },
    { name: '@captured_visits_traffic_page', desc: 'รูปภาพกราฟสถิติ HTTP Traffic เฉพาะ Visits', example: '<img>', category: 'Traffic Screenshots' },
    { name: '@captured_api_requests_traffic_page', desc: 'รูปภาพกราฟสถิติ HTTP Traffic เฉพาะ API Requests', example: '<img>', category: 'Traffic Screenshots' },
];

export const STATIC_VARIABLES = [
    { name: '@DAY', desc: 'วันที่ปัจจุบัน', example: '17', category: 'Basic' },
    { name: '@MONTH', desc: 'เดือนปัจจุบัน (ไทย)', example: 'กุมภาพันธ์', category: 'Basic' },
    { name: '@YEAR', desc: 'ปี พ.ศ. ปัจจุบัน', example: '2569', category: 'Basic' },
    { name: '@FULL_DATE', desc: 'วันที่แบบเต็ม (ไทย)', example: '17 กุมภาพันธ์ 2569', category: 'Basic' },
    { name: '@ACCOUNT_NAME', desc: 'ชื่อ Account', example: 'My Account', category: 'Basic' },
    { name: '@ZONE_NAME', desc: 'ชื่อ Zone', example: 'example.com', category: 'Basic' },
    { name: '@DNS_RECORDS', desc: 'รายการ DNS Record (Proxied)', example: 'A example.com Proxied', category: 'DNS' },
    { name: '@DNS_TOTAL_ROWS', desc: 'ตาราง DNS ทั้งหมด (Auto Replace)', example: '<tr>...</tr>', category: 'DNS' },
    { name: '@SECURITY_LEVEL', desc: 'ระดับความปลอดภัย (Security Level)', example: 'Medium', category: 'Security' },
    { name: '@BOT_MANAGEMENT_STATUS', desc: 'สถานะ Bot Management', example: 'Enabled', category: 'Security' },
    { name: '@BLOCK_AI_BOTS', desc: 'การบล็อก AI Bots', example: 'Yes', category: 'Security' },
    { name: '@DEFINITELY_AUTOMATED', desc: 'Action สำหรับ Definitely Automated', example: 'Block', category: 'Security' },
    { name: '@LIKELY_AUTOMATED', desc: 'Action สำหรับ Likely Automated', example: 'Managed Challenge', category: 'Security' },
    { name: '@VERIFIED_BOTS', desc: 'Action สำหรับ Verified Bots', example: 'Allow', category: 'Security' },
    { name: '@CLOUDFLARE_MANAGED_RULESET', desc: 'สถานะ Cloudflare Managed Ruleset', example: 'Enabled', category: 'WAF' },
    { name: '@OWASP_CORE_RULESET', desc: 'สถานะ OWASP Core Ruleset', example: 'Enabled', category: 'WAF' },
    { name: '@MANAGED_RULES_COUNT', desc: 'จำนวน Managed Rules ที่เปิดใช้งาน', example: '15', category: 'WAF' },
    { name: '@HTTP_DDOS_PROTECTION', desc: 'สถานะ HTTP DDoS Protection', example: 'Enabled', category: 'DDoS' },
    { name: '@SSL_TLS_DDOS_PROTECTION', desc: 'สถานะ SSL/TLS DDoS Protection', example: 'Enabled', category: 'DDoS' },
    { name: '@NETWORK_DDOS_PROTECTION', desc: 'สถานะ Network DDoS Protection', example: 'Enabled', category: 'DDoS' },
    { name: '@DDOS_PROTECTION', desc: 'สถานะรวม DDoS Protection', example: 'Enable', category: 'DDoS' },
    { name: '@IP_ACCESS_RULES_ROWS', desc: 'ตาราง IP Access Rules', example: '<tr>...</tr>', category: 'Rules' },
    { name: '@CUSTOM_RULES_ROWS', desc: 'ตาราง Custom Rules', example: '<tr>...</tr>', category: 'Rules' },
    { name: '@RATE_LIMITING_RULES_ROWS', desc: 'ตาราง Rate Limiting Rules', example: '<tr>...</tr>', category: 'Rules' },
    { name: '@SSL_MODE', desc: 'โหมด SSL/TLS', example: 'Full (Strict)', category: 'SSL' },
    { name: '@MIN_TLS_VERSION', desc: 'เวอร์ชัน TLS ขั้นต่ำ', example: '1.2', category: 'SSL' },
    { name: '@TLS_1_3', desc: 'สถานะ TLS 1.3', example: 'Enabled', category: 'SSL' },
    { name: '@LEAKED_CREDENTIALS', desc: 'Leaked Credentials Detection', example: 'Enabled', category: 'More' },
    { name: '@BROWSER_INTEGRITY_CHECK', desc: 'Browser Integrity Check', example: 'Enabled', category: 'More' },
    { name: '@HOTLINK_PROTECTION', desc: 'Hotlink Protection', example: 'Disabled', category: 'More' },
    { name: '@DOMAIN_COUNT', desc: 'จำนวนโดเมนทั้งหมดใน Account', example: '20', category: 'Basic' },
    { name: '@SUBDOMAIN_COUNT', desc: 'จำนวน Subdomain ทั้งหมดใน Zone', example: '15', category: 'DNS' },
    { name: '@PROXIED_COUNT', desc: 'จำนวน Subdomain ที่เปิดใช้งาน Proxy', example: '8', category: 'DNS' },
    { name: '@TOP_COUNTRY_REQ', desc: 'จำนวน Request จากประเทศที่ใช้งานมากที่สุด', example: '21,970,000', category: 'DNS' },
    { name: '@VISITS', desc: 'จำนวนผู้เข้าชมทั้งหมด (Visits/Uniques)', example: '3,670,000', category: 'DNS' },
    { name: '@PAGE_VIEWS', desc: 'จำนวน Page Views ทั้งหมด', example: '7,980,000', category: 'DNS' },
    { name: '@SUBDOMAIN_TOTAL_REQ_M', desc: 'จำนวน Request ทั้งหมดในหน่วยล้าน (เช่น 39.06M)', example: '39.06M', category: 'DNS' },
    { name: '@ZONE_TOTAL_REQ_M', desc: 'Total Request ของ Zone ในหน่วยล้าน (เช่น 39.06M)', example: '39.06M', category: 'DNS' },
    { name: '@PAGE_VIEWS_M', desc: 'จำนวน Page Views ทั้งหมดในหน่วยล้าน (เช่น 7.98M)', example: '7.98M', category: 'DNS' },
    { name: '@TRAFFIC_CHANGE_TEXT', desc: 'แนวโน้มการเปลี่ยนแปลง Traffic (เช่น เพิ่มขึ้น / ลดลง)', example: 'เพิ่มขึ้น', category: 'DNS' },
    { name: '@TRAFFIC_CHANGE_PCT', desc: 'เปอร์เซ็นต์การเปลี่ยนแปลงของ Traffic (เทียบกับรอบก่อนหน้า)', example: '1.79%', category: 'DNS' },
    { name: '@REQ_PER_PAGEVIEW_PCT', desc: 'อัตราส่วน Request ต่อ Page View (%)', example: '489.47%', category: 'DNS' },
    { name: '@TOTAL_DATA_TRANSFER', desc: 'ปริมาณการโอนย้ายข้อมูลทั้งหมด (Data Transfer)', example: '2.46 TB', category: 'DNS' },
    { name: '@DATA_TRANSFER_CHANGE_TEXT', desc: 'แนวโน้มการเปลี่ยนแปลง Data Transfer (เช่น เพิ่มขึ้น / ลดลง)', example: 'ลดลง', category: 'DNS' },
    { name: '@DATA_TRANSFER_CHANGE_PCT', desc: 'เปอร์เซ็นต์การเปลี่ยนแปลงของ Data Transfer (เทียบกับรอบก่อนหน้า)', example: '17.43%', category: 'DNS' },
    { name: '@FW_LOG_COUNT', desc: 'จำนวนการจัดการ Traffic แบบ Log (การบันทึก)', example: '1.43M', category: 'DNS' },
    { name: '@FW_SKIP_COUNT', desc: 'จำนวนการจัดการ Traffic แบบ Skip (การข้ามตรวจสอบ)', example: '3.76k', category: 'DNS' },
    { name: '@FW_CHALLENGE_COUNT', desc: 'จำนวนการจัดการ Traffic แบบ Managed Challenge (การท้าทายตรวจสอบ)', example: '6.1k', category: 'DNS' },
    { name: '@FW_BLOCK_COUNT', desc: 'จำนวนการจัดการ Traffic แบบ Block (การปิดกั้น)', example: '0', category: 'DNS' },
    { name: '@ARGO_IMPROVEMENT_PCT', desc: 'เปอร์เซ็นต์ประสิทธิภาพที่เพิ่มขึ้นโดยเฉลี่ยของ Argo', example: '29.84%', category: 'Argo' },
    { name: '@ARGO_RT_BEFORE', desc: 'Response Time จากทางฝั่ง Server ก่อนเปิดใช้ Argo', example: '1.15 s', category: 'Argo' },
    { name: '@ARGO_RT_AFTER', desc: 'Response Time จากทางฝั่ง Server หลังเปิดใช้ Argo', example: '804 ms', category: 'Argo' },
    { name: '@SPEED_TTI', desc: 'เวลาในการโต้ตอบหลัก (Time to Interactive) จากการทดสอบความเร็ว', example: '1,221 ms', category: 'Speed' },
    { name: '@SPEED_INDEX', desc: 'ความเร็วเฉลี่ยในการแสดงผลหน้าเว็บ (Speed Index)', example: '1,165 ms', category: 'Speed' },
    { name: '@SPEED_SCORE', desc: 'คะแนนประสิทธิภาพรวมในการทดสอบความเร็ว (%)', example: '97%', category: 'Speed' },
    { name: '@SPEED_LEVEL', desc: 'ระดับคะแนนประสิทธิภาพความเร็ว (เช่น ดีเยี่ยม / ดี / ปานกลาง)', example: 'ดีเยี่ยม', category: 'Speed' },
    { name: '@SPEED_MOBILE_TTI', desc: 'เวลาในการโต้ตอบหลักสำหรับมือถือ (Mobile Time to Interactive) จากการทดสอบความเร็ว', example: '5,924 ms', category: 'Speed' },
    { name: '@SPEED_MOBILE_INDEX', desc: 'ความเร็วเฉลี่ยในการแสดงผลหน้าเว็บสำหรับมือถือ (Mobile Speed Index)', example: '3,259 ms', category: 'Speed' },
    { name: '@SPEED_MOBILE_SCORE', desc: 'คะแนนประสิทธิภาพรวมสำหรับมือถือในการทดสอบความเร็ว (%)', example: '67%', category: 'Speed' },
    { name: '@SPEED_MOBILE_LEVEL', desc: 'ระดับคะแนนประสิทธิภาพความเร็วสำหรับมือถือ (เช่น ดีเยี่ยม / ดี / ปานกลาง / กลาง)', example: 'กลาง', category: 'Speed' },
    { name: '@PAGE_BREAK@', desc: 'ตัวคั่นหน้ากระดาษ', example: '<br.../>', category: 'Format' },
    { name: '@TOC@', desc: 'สารบัญอัตโนมัติ (เลือกวางจุดใดก็ได้ในเทมเพลต)', example: '<div>...</div>', category: 'Format' },
    { name: '@captured_domain_page', desc: 'รูปภาพหน้าจอหน้ารวมโดเมน (Sites overview)', example: '<img>', category: 'Screenshots' },
    { name: '@captured_dns_page', desc: 'รูปภาพหน้าจอรายการ DNS Records', example: '<img>', category: 'Screenshots' },
    { name: '@captured_firewall_page', desc: 'รูปภาพหน้าจอความปลอดภัยและเหตุการณ์ WAF (Firewall Overview)', example: '<img>', category: 'Screenshots' },
    { name: '@captured_security_rules_page', desc: 'รูปภาพหน้าจอรายการกฎความปลอดภัย (Security Custom Rules)', example: '<img>', category: 'Screenshots' },
    { name: '@captured_argo_page', desc: 'รูปภาพหน้าจอการตั้งค่า Argo Smart Routing', example: '<img>', category: 'Screenshots' },
    { name: '@captured_speed_page', desc: 'รูปภาพหน้าจอผลการทดสอบความเร็วเว็บไซต์ (Speed Test)', example: '<img>', category: 'Screenshots' },
    { name: '@captured_speed_mobile_page', desc: 'รูปภาพหน้าจอผลการทดสอบความเร็วบนมือถือ (Speed Test Mobile)', example: '<img>', category: 'Screenshots' },
    { name: '@captured_request_traffic_page', desc: 'รูปภาพกราฟสถิติ HTTP Traffic เฉพาะ Requests', example: '<img>', category: 'Traffic Screenshots' },
    { name: '@captured_data_transfer_traffic_page', desc: 'รูปภาพกราฟสถิติ HTTP Traffic เฉพาะ Data Transfer', example: '<img>', category: 'Traffic Screenshots' },
    { name: '@captured_page_views_traffic_page', desc: 'รูปภาพกราฟสถิติ HTTP Traffic เฉพาะ Page Views', example: '<img>', category: 'Traffic Screenshots' },
    { name: '@captured_visits_traffic_page', desc: 'รูปภาพกราฟสถิติ HTTP Traffic เฉพาะ Visits', example: '<img>', category: 'Traffic Screenshots' },
    { name: '@captured_api_requests_traffic_page', desc: 'รูปภาพกราฟสถิติ HTTP Traffic เฉพาะ API Requests', example: '<img>', category: 'Traffic Screenshots' },
    { name: '@captured_traffic_page', desc: 'รูปภาพหน้าจอหน้ารวม Traffic ทั้งหมด', example: '<img>', category: 'Screenshots' },
    { name: '@TOTAL_REQ', desc: 'จำนวน Request ทั้งหมด', example: '1,234,567', category: 'Basic' },
    { name: '@TOP_COUNTRY_VAL', desc: 'ประเทศที่ใช้งานมากที่สุด (อันดับ 1)', example: 'Thailand', category: 'Basic' },
    { name: '@TOP_COUNTRY_REQ_COUNT', desc: 'จำนวน Request จากประเทศอันดับ 1', example: '21,970,000', category: 'Basic' },
    { name: '@TOTAL_BANDWIDTH', desc: 'ปริมาณการโอนย้ายข้อมูลทั้งหมด (Bandwidth)', example: '2.46 TB', category: 'Basic' },
    { name: '@FW_RULE_KNOWN_BOTS_COUNT', desc: 'จำนวนเหตุการณ์บอทที่รู้จัก (Known Bots Skip)', example: '1,200', category: 'Firewall Rules' },
    { name: '@FW_RULE_DTT_COUNT', desc: 'จำนวน DTT Skip 1000req/min', example: '350', category: 'Firewall Rules' },
    { name: '@FW_RULE_GIS_COUNT', desc: 'จำนวน GIS Skip 1000req/min', example: '80', category: 'Firewall Rules' },
    { name: '@FW_RULE_NOT_THAI_COUNT', desc: 'จำนวน Not Thailand Challenge', example: '450', category: 'Firewall Rules' },
    { name: '@FW_RULE_ALL_LOG_COUNT', desc: 'จำนวน All Log', example: '15,000', category: 'Firewall Rules' },
    { name: '@FW_RULE_SKIP_REGISTER_LOGIN_COUNT', desc: 'จำนวน Skip Register Login', example: '1,100', category: 'Firewall Rules' },
    { name: '@FW_RULE_SKIP_RATELIMIT_COUNT', desc: 'จำนวน Skip Ratelimit', example: '950', category: 'Firewall Rules' },
    { name: '@FW_RULE_SKIP_ATTACHMENT_COUNT', desc: 'จำนวน Skip Attachment', example: '150', category: 'Firewall Rules' },
    { name: '@FW_RULE_SKIP_LICENSEFEE_COUNT', desc: 'จำนวน Skip Licensefee', example: '200', category: 'Firewall Rules' },
    { name: '@FW_RULE_RATELIMIT_300_COUNT', desc: 'จำนวน 300req/1min Challenge', example: '50', category: 'Firewall Rules' },
];
