export const REPORT_VARIABLES = [
    { name: '@DAY', desc: 'วันที่ปัจจุบัน (1-31)', example: '17', category: 'Time' },
    { name: '@MONTH', desc: 'เดือนปัจจุบัน (ภาษาไทย)', example: 'กุมภาพันธ์', category: 'Time' },
    { name: '@YEAR', desc: 'ปี พ.ศ. ปัจจุบัน', example: '2569', category: 'Time' },
    { name: '@FULL_DATE', desc: 'วันที่แบบเต็ม (ไทย)', example: '17 กุมภาพันธ์ 2569', category: 'Time' },
    { name: '@TIME_RANGE', desc: 'ช่วงเวลาของข้อมูลในรายงาน', example: '16/02/69 - 17/02/69', category: 'Time' },
    { name: '@DOMAIN', desc: 'ชื่อโดเมน (หรือ "ทุก Subdomain")', example: 'example.com', category: 'Info' },
    { name: '@ACCOUNT_NAME', desc: 'ชื่อ Account Cloudflare', example: 'My Company', category: 'Info' },
    { name: '@ZONE_NAME', desc: 'ชื่อ Zone', example: 'example.com', category: 'Info' },
    { name: '@TOTAL_REQ', desc: 'จำนวน Request ทั้งหมด', example: '1,234,567', category: 'Stats' },
    { name: '@AVG_TIME', desc: 'เวลาตอบสนองเฉลี่ย (วินาที)', example: '0.450', category: 'Stats' },
    { name: '@BLOCK_PCT', desc: 'เปอร์เซ็นต์การ Block', example: '12.50', category: 'Stats' },
    { name: '@LOG_PCT', desc: 'เปอร์เซ็นต์การ Log', example: '5.00', category: 'Stats' },
    { name: '@PEAK_TIME', desc: 'เวลาที่มีการใช้งานสูงสุด', example: '14:30', category: 'Peak' },
    { name: '@PEAK_COUNT', desc: 'จำนวน Request สูงสุด ณ เวลา Peak', example: '5,000', category: 'Peak' },
    { name: '@PEAK_ATTACK_TIME', desc: 'เวลาที่มีการโจมตีสูงสุด', example: '02:15', category: 'Peak' },
    { name: '@PEAK_ATTACK_COUNT', desc: 'จำนวนการโจมตีสูงสุด', example: '800', category: 'Peak' },
    { name: '@PEAK_HTTP_TIME', desc: 'เวลาที่มี HTTP Status (Error) สูงสุด', example: '10:00', category: 'Peak' },
    { name: '@PEAK_HTTP_COUNT', desc: 'จำนวน HTTP Status สูงสุด', example: '200', category: 'Peak' },
    { name: '@TOP_UA_AGENT', desc: 'User Agent ที่พบบ่อยที่สุด', example: 'Mozilla/5.0...', category: 'Top' },
    { name: '@TOP_UA_COUNT', desc: 'จำนวนครั้งของ User Agent นั้น', example: '15,000', category: 'Top' },
    { name: '@TOP_IP_VAL', desc: 'IP ที่ใช้งานมากที่สุด (อันดับ 1)', example: '192.168.1.1', category: 'Top' },
    { name: '@TOP_UA_VAL', desc: 'User Agent อันดับ 1', example: 'Chrome...', category: 'Top' },
    { name: '@TOP_COUNTRY_VAL', desc: 'ประเทศที่ใช้งานมากที่สุด (อันดับ 1)', example: 'Thailand', category: 'Top' },
    { name: '@TOP_HOST_VAL', desc: 'Host ที่ถูกเรียกมากที่สุด (อันดับ 1)', example: 'api.example.com', category: 'Top' },
    { name: '@TOP_URLS_LIST', desc: 'ตาราง 3 อันดับ URL ยอดนิยม', example: '<table>...</table>', category: 'Table' },
    { name: '@TOP_IPS_LIST', desc: 'ตาราง 3 อันดับ Client IP', example: '<table>...</table>', category: 'Table' },
    { name: '@TOP_RULES_LIST', desc: 'ตาราง 3 อันดับ WAF Rule ที่ทำงาน', example: '<table>...</table>', category: 'Table' },
    { name: '@TOP_ATTACKERS_LIST', desc: 'ตาราง 5 อันดับผู้โจมตี', example: '<table>...</table>', category: 'Table' },
    { name: '@TOP_SOURCES_LIST', desc: 'ตาราง 5 อันดับ Security Source', example: '<table>...</table>', category: 'Table' },
    { name: '@TOP_PATHS_LIST', desc: 'รายการ Top 5 Paths (List)', example: '<ol>...</ol>', category: 'List' },
    { name: '@TOP_CUSTOM_RULES_LIST', desc: 'รายการ Top Custom Rules (List)', example: '<ol>...</ol>', category: 'List' },
    { name: '@TOP_MANAGED_RULES_LIST', desc: 'รายการ Top Managed Rules (List)', example: '<ol>...</ol>', category: 'List' },
    { name: '@ZONE_TOTAL_REQ', desc: 'Total Request ของ Zone (Caching)', example: '10M', category: 'Zone Cache' },
    { name: '@ZONE_CACHE_HIT_REQ', desc: 'Cache Hit Requests', example: '8M', category: 'Zone Cache' },
    { name: '@ZONE_CACHE_HIT_REQ_RATIO', desc: 'Ratio Cache Hit Requests', example: '80%', category: 'Zone Cache' },
    { name: '@ZONE_TOTAL_BANDWIDTH', desc: 'Total Bandwidth', example: '50 GB', category: 'Zone Cache' },
    { name: '@ZONE_CACHE_HIT_BANDWIDTH', desc: 'Cache Hit Bandwidth', example: '20 GB', category: 'Zone Cache' },
    { name: '@ZONE_CACHE_HIT_BANDWIDTH_RATIO', desc: 'Ratio Cache Hit Bandwidth', example: '40%', category: 'Zone Cache' },
    { name: '@ZONE_TOP_COUNTRIES_REQ', desc: 'Top Countries by Request (List)', example: '<ol>...</ol>', category: 'Zone Cache' },
    { name: '@ZONE_TOP_COUNTRIES_BYTES', desc: 'Top Countries by Bytes (List)', example: '<ol>...</ol>', category: 'Zone Cache' },
    { name: '@FW_TOTAL_EVENTS', desc: 'รวมเหตุการณ์ Firewall ทั้งหมด', example: '150k', category: 'Firewall' },
    { name: '@FW_MANAGED_EVENTS', desc: 'Managed Rules Events', example: '10k', category: 'Firewall' },
    { name: '@FW_CUSTOM_EVENTS', desc: 'Custom Rules Events', example: '5k', category: 'Firewall' },
    { name: '@FW_BIC_EVENTS', desc: 'Browser Integrity Check Events', example: '1k', category: 'Firewall' },
    { name: '@FW_ACCESS_EVENTS', desc: 'Access Rules Events', example: '500', category: 'Firewall' },
    { name: '@PAGE_BREAK@', desc: 'ตัวคั่นหน้ากระดาษ (Word)', example: '<br page-break.../>', category: 'Format' },
    { name: '@DASHBOARD_IMAGE@', desc: 'รูปภาพ Dashboard Snapshot', example: '<img>', category: 'Format' },
];

export const STATIC_VARIABLES = [
    { name: '@DAY', desc: 'วันที่ปัจจุบัน', example: '17', category: 'Basic' },
    { name: '@MONTH', desc: 'เดือนปัจจุบัน (ไทย)', example: 'กุมภาพันธ์', category: 'Basic' },
    { name: '@YEAR', desc: 'ปี พ.ศ. ปัจจุบัน', example: '2569', category: 'Basic' },
    { name: '@FULL_DATE', desc: 'วันที่แบบเต็ม (ไทย)', example: '17 กุมภาพันธ์ 2569', category: 'Basic' },
    { name: '@ACCOUNT_NAME', desc: 'ชื่อ Account', example: 'My Account', category: 'Basic' },
    { name: '@ZONE_NAME', desc: 'ชื่อ Zone', example: 'example.com', category: 'Basic' },
    { name: '@DNS_RECORDS', desc: 'รายการ DNS Record (Proxied)', example: 'A example.com Proxied', category: 'DNS' },
    { name: '@DNS_TOTAL_ROWS', desc: 'ตาราง DNS ทั้งหมด (Auto Replace)', example: '<tr>...</tr>', category: 'DNS' },
    { name: '@SECURITY_LEVEL', desc: 'ระดับความปลอดภัย (Security Level)', example: 'Medium', category: 'Security' },
    { name: '@BOT_MANAGEMENT_STATUS', desc: 'สถานะ Bot Management', example: 'Enabled', category: 'Security' },
    { name: '@BLOCK_AI_BOTS', desc: 'การบล็อก AI Bots', example: 'Yes', category: 'Security' },
    { name: '@DEFINITELY_AUTOMATED', desc: 'Action สำหรับ Definitely Automated', example: 'Block', category: 'Security' },
    { name: '@LIKELY_AUTOMATED', desc: 'Action สำหรับ Likely Automated', example: 'Managed Challenge', category: 'Security' },
    { name: '@VERIFIED_BOTS', desc: 'Action สำหรับ Verified Bots', example: 'Allow', category: 'Security' },
    { name: '@CLOUDFLARE_MANAGED_RULESET', desc: 'สถานะ Cloudflare Managed Ruleset', example: 'Enabled', category: 'WAF' },
    { name: '@OWASP_CORE_RULESET', desc: 'สถานะ OWASP Core Ruleset', example: 'Enabled', category: 'WAF' },
    { name: '@MANAGED_RULES_COUNT', desc: 'จำนวน Managed Rules ที่เปิดใช้งาน', example: '15', category: 'WAF' },
    { name: '@HTTP_DDOS_PROTECTION', desc: 'สถานะ HTTP DDoS Protection', example: 'Enabled', category: 'DDoS' },
    { name: '@SSL_TLS_DDOS_PROTECTION', desc: 'สถานะ SSL/TLS DDoS Protection', example: 'Enabled', category: 'DDoS' },
    { name: '@NETWORK_DDOS_PROTECTION', desc: 'สถานะ Network DDoS Protection', example: 'Enabled', category: 'DDoS' },
    { name: '@DDOS_PROTECTION', desc: 'สถานะรวม DDoS Protection', example: 'Enable', category: 'DDoS' },
    { name: '@IP_ACCESS_RULES_ROWS', desc: 'ตาราง IP Access Rules', example: '<tr>...</tr>', category: 'Rules' },
    { name: '@CUSTOM_RULES_ROWS', desc: 'ตาราง Custom Rules', example: '<tr>...</tr>', category: 'Rules' },
    { name: '@RATE_LIMITING_RULES_ROWS', desc: 'ตาราง Rate Limiting Rules', example: '<tr>...</tr>', category: 'Rules' },
    { name: '@SSL_MODE', desc: 'โหมด SSL/TLS', example: 'Full (Strict)', category: 'SSL' },
    { name: '@MIN_TLS_VERSION', desc: 'เวอร์ชัน TLS ขั้นต่ำ', example: '1.2', category: 'SSL' },
    { name: '@TLS_1_3', desc: 'สถานะ TLS 1.3', example: 'Enabled', category: 'SSL' },
    { name: '@LEAKED_CREDENTIALS', desc: 'Leaked Credentials Detection', example: 'Enabled', category: 'More' },
    { name: '@BROWSER_INTEGRITY_CHECK', desc: 'Browser Integrity Check', example: 'Enabled', category: 'More' },
    { name: '@HOTLINK_PROTECTION', desc: 'Hotlink Protection', example: 'Disabled', category: 'More' },
    { name: '@PAGE_BREAK@', desc: 'ตัวคั่นหน้ากระดาษ', example: '<br.../>', category: 'Format' },
];
